export {default as Popular} from './Popular_Page'
export {default as DetailPage} from './Detail_Page'
export {default as NowPlaying} from './Now_Playing_Page'
export {default as TopRated} from './Top_Rated_Page'
export {default as UpcomingPage} from './Upcoming_Page'
export {default as WishlistPage} from './Wishlist_Page'
export {default as WatchlistPage} from './WatchList_Page'
